[package]
name = "md4"
version = "0.1.0"
authors = ["glatan <glatan@protonmail.com>"]
edition = "2018"

[features]
# 出力バイナリサイズが小さい(主にwasmターゲットでの使用を推奨)
minimal = []

[dependencies]
utils = { path = "../../utils" }

[dev-dependencies]
dev-utils = { path = "../../dev-utils" }
