stages:
  - test

variables:
  CARGO_HOME: ${CI_PROJECT_DIR}/cargo
  WASMTIME_VERSION: 0.15.0

before_script:
  - rustc --version

cache:
  paths:
    - cargo/
    - target/

.wasm32-wasi_template: &wasm32-wasi_template
  before_script:
    - rustc --version
    # add target
    - rustup target add wasm32-wasi
    # install wasmtime
    - apt update -y
    - apt install -y curl xz-utils
    - curl -L "https://github.com/bytecodealliance/wasmtime/releases/download/v${WASMTIME_VERSION}/wasmtime-v${WASMTIME_VERSION}-x86_64-linux.tar.xz" > wasmtime-v${WASMTIME_VERSION}-x86_64-linux.tar.xz
    - tar -xvf wasmtime-v${WASMTIME_VERSION}-x86_64-linux.tar.xz
    - mv wasmtime-v${WASMTIME_VERSION}-x86_64-linux/wasmtime /usr/bin/
  script:
    - cargo test --lib --verbose --target wasm32-wasi

stable-i686-unknown-linux-gnu:
  stage: test
  image: i386/rust:slim-buster
  script:
    - cargo test --verbose --target i686-unknown-linux-gnu

stable-x86_64-unknown-linux-gnu:
  stage: test
  image: amd64/rust:slim-buster
  script:
    - cargo test --verbose --target x86_64-unknown-linux-gnu

stable-wasm32-wasi:
  stage: test
  image: amd64/rust:slim-buster
  <<: *wasm32-wasi_template

nightly-x86_64-unknown-linux-gnu:
  stage: test
  image: rustlang/rust:nightly-buster-slim
  script:
    - cargo test --verbose --target x86_64-unknown-linux-gnu

nightly-wasm32-wasi:
  stage: test
  image: rustlang/rust:nightly-buster-slim
  <<: *wasm32-wasi_template
