stages:
  - test

variables:
  CARGO_HOME: ${CI_PROJECT_DIR}/cargo

.cross_compile_template: &cross_compile_template
  image: amd64/debian:buster-slim
  cache:
    paths:
      - target/${TARGET}
  before_script:
    - apt update -y
    - apt install -y curl make qemu-user ${PACKAGES}
    - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > setup.sh
    - sh setup.sh -y -t ${TARGET} --default-toolchain stable --profile minimal
    - source ${CI_PROJECT_DIR}/cargo/env
  script:
    - make test.${TARGET}

.wasm32-wasi_template: &wasm32-wasi_template
  variables:
    WASMTIME_VERSION: 0.20.0
  cache:
    paths:
      - target/wasm32-wasi
  before_script:
    - rustc --version
    - rustup target add wasm32-wasi
    - apt update -y
    - apt install -y curl make xz-utils
    - curl -L "https://github.com/bytecodealliance/wasmtime/releases/download/v${WASMTIME_VERSION}/wasmtime-v${WASMTIME_VERSION}-x86_64-linux.tar.xz" > wasmtime-v${WASMTIME_VERSION}-x86_64-linux.tar.xz
    - tar -xvf wasmtime-v${WASMTIME_VERSION}-x86_64-linux.tar.xz
    - mv wasmtime-v${WASMTIME_VERSION}-x86_64-linux/wasmtime /usr/bin/
  script:
    - make test.wasm32-wasi

stable-aarch64-unknown-linux-gnu:
  variables:
    PACKAGES: gcc-aarch64-linux-gnu
    TARGET: aarch64-unknown-linux-gnu
  <<: *cross_compile_template

stable-arm-unknown-linux-gnueabi:
  variables:
    PACKAGES: gcc-arm-linux-gnueabi
    TARGET: arm-unknown-linux-gnueabi
  <<: *cross_compile_template

stable-arm-unknown-linux-gnueabihf:
  variables:
    PACKAGES: gcc-arm-linux-gnueabihf
    TARGET: arm-unknown-linux-gnueabihf
  <<: *cross_compile_template

stable-armv5te-unknown-linux-gnueabi:
  variables:
    PACKAGES: gcc-arm-linux-gnueabi
    TARGET: armv5te-unknown-linux-gnueabi
  <<: *cross_compile_template

stable-armv7-unknown-linux-gnueabi:
  variables:
    PACKAGES: gcc-arm-linux-gnueabi
    TARGET: armv7-unknown-linux-gnueabi
  <<: *cross_compile_template

stable-armv7-unknown-linux-gnueabihf:
  variables:
    PACKAGES: gcc-arm-linux-gnueabihf
    TARGET: armv7-unknown-linux-gnueabihf
  <<: *cross_compile_template

stable-i586-unknown-linux-gnu:
  variables:
    PACKAGES: gcc-i686-linux-gnu
    TARGET: i586-unknown-linux-gnu
  <<: *cross_compile_template

stable-i686-unknown-linux-gnu:
  variables:
    PACKAGES: gcc-i686-linux-gnu
    TARGET: i686-unknown-linux-gnu
  <<: *cross_compile_template

stable-mips-unknown-linux-gnu:
  variables:
    PACKAGES: gcc-mips-linux-gnu
    TARGET: mips-unknown-linux-gnu
  <<: *cross_compile_template

stable-mipsel-unknown-linux-gnu:
  variables:
    PACKAGES: gcc-mipsel-linux-gnu
    TARGET: mipsel-unknown-linux-gnu
  <<: *cross_compile_template

stable-mips64-unknown-linux-gnuabi64:
  variables:
    PACKAGES: gcc-mips64-linux-gnuabi64
    TARGET: mips64-unknown-linux-gnuabi64
  <<: *cross_compile_template

stable-mips64el-unknown-linux-gnuabi64:
  variables:
    PACKAGES: gcc-mips64el-linux-gnuabi64
    TARGET: mips64el-unknown-linux-gnuabi64
  <<: *cross_compile_template

stable-powerpc64le-unknown-linux-gnu:
  variables:
    PACKAGES: gcc-powerpc64le-linux-gnu
    TARGET: powerpc64le-unknown-linux-gnu
  <<: *cross_compile_template

stable-riscv64gc-unknown-linux-gnu:
  variables:
    PACKAGES: gcc-riscv64-linux-gnu
    TARGET: riscv64gc-unknown-linux-gnu
  <<: *cross_compile_template

stable-s390x-unknown-linux-gnu:
  variables:
    PACKAGES: gcc-s390x-linux-gnu
    TARGET: s390x-unknown-linux-gnu
  <<: *cross_compile_template

stable-sparc64-unknown-linux-gnu:
  variables:
    PACKAGES: gcc-sparc64-linux-gnu
    TARGET: sparc64-unknown-linux-gnu
  <<: *cross_compile_template

stable-x86_64-unknown-linux-gnu:
  stage: test
  image: amd64/rust:slim-buster
  cache:
    paths:
      - target/x86_64-unknown-linux-gnu
  before_script:
    - apt update -y
    - apt install -y make
    - rustc --version
  script:
    - make test.x86_64-unknown-linux-gnu

stable-wasm32-wasi:
  stage: test
  image: amd64/rust:slim-buster
  <<: *wasm32-wasi_template

nightly-x86_64-unknown-linux-gnu:
  stage: test
  image: rustlang/rust:nightly-buster-slim
  cache:
    paths:
      - target/x86_64-unknown-linux-gnu
  before_script:
    - apt update -y
    - apt install -y make
    - rustc --version
  script:
    - make test.x86_64-unknown-linux-gnu

nightly-wasm32-wasi:
  stage: test
  image: rustlang/rust:nightly-buster-slim
  <<: *wasm32-wasi_template
