stages:
  - stable
  - msrv # Minimum Supported Rust Version
  - nightly

variables:
  CARGO_HOME: ${CI_PROJECT_DIR}/cargo
  MSRV: '1.43'

# Templates

.cross_compile_template: &cross_compile_template
  image: ubuntu:groovy
  cache:
    key: ${CI_JOB_STAGE}-${TARGET}
    paths:
      - target/${TARGET}
  before_script:
    - >
      apt update -y;
      apt install -y curl make;
      curl https://sh.rustup.rs -sSf > install.sh;
      sh install.sh -y --default-toolchain ${CHANNEL} --profile minimal -t ${TARGET};
      if [[ ${#PACKAGES[@]} -ne 0 ]]; then
        apt install -y qemu-user ${PACKAGES};
      fi;
  script:
    - source ${CARGO_HOME}/env
    - make test.${TARGET}

.matrix_template: &matrix_template
  parallel:
    matrix:
      - PACKAGES: gcc-aarch64-linux-gnu
        TARGET: aarch64-unknown-linux-gnu
      - PACKAGES: gcc-arm-linux-gnueabi
        TARGET: arm-unknown-linux-gnueabi


stable-test:
  stage: stable
  variables:
    CHANNEL: stable
  <<: *cross_compile_template
  <<: *matrix_template
