stages:
  - stable
  - msrv # Minimum Supported Rust Version
  - nightly

variables:
  CARGO_HOME: ${CI_PROJECT_DIR}/cargo

include:
  - local: /ci/template.yml

# Stable

## Linux

stable-aarch64-unknown-linux-gnu:
  variables:
    PACKAGES: gcc-aarch64-linux-gnu
    TARGET: aarch64-unknown-linux-gnu
  <<: *stable_cross_compile_template

stable-arm-unknown-linux-gnueabi:
  variables:
    PACKAGES: gcc-arm-linux-gnueabi
    TARGET: arm-unknown-linux-gnueabi
  <<: *stable_cross_compile_template

stable-arm-unknown-linux-gnueabihf:
  variables:
    PACKAGES: gcc-arm-linux-gnueabihf
    TARGET: arm-unknown-linux-gnueabihf
  <<: *stable_cross_compile_template

stable-armv5te-unknown-linux-gnueabi:
  variables:
    PACKAGES: gcc-arm-linux-gnueabi
    TARGET: armv5te-unknown-linux-gnueabi
  <<: *stable_cross_compile_template

stable-armv7-unknown-linux-gnueabi:
  variables:
    PACKAGES: gcc-arm-linux-gnueabi
    TARGET: armv7-unknown-linux-gnueabi
  <<: *stable_cross_compile_template

stable-armv7-unknown-linux-gnueabihf:
  variables:
    PACKAGES: gcc-arm-linux-gnueabihf
    TARGET: armv7-unknown-linux-gnueabihf
  <<: *stable_cross_compile_template

stable-i586-unknown-linux-gnu:
  variables:
    PACKAGES: gcc-i686-linux-gnu
    TARGET: i586-unknown-linux-gnu
  <<: *stable_cross_compile_template

stable-i686-unknown-linux-gnu:
  variables:
    PACKAGES: gcc-i686-linux-gnu
    TARGET: i686-unknown-linux-gnu
  <<: *stable_cross_compile_template

stable-mips-unknown-linux-gnu:
  variables:
    PACKAGES: gcc-mips-linux-gnu
    TARGET: mips-unknown-linux-gnu
  <<: *stable_cross_compile_template

stable-mipsel-unknown-linux-gnu:
  variables:
    PACKAGES: gcc-mipsel-linux-gnu
    TARGET: mipsel-unknown-linux-gnu
  <<: *stable_cross_compile_template

stable-mips64-unknown-linux-gnuabi64:
  variables:
    PACKAGES: gcc-mips64-linux-gnuabi64
    TARGET: mips64-unknown-linux-gnuabi64
  <<: *stable_cross_compile_template

stable-mips64el-unknown-linux-gnuabi64:
  variables:
    PACKAGES: gcc-mips64el-linux-gnuabi64
    TARGET: mips64el-unknown-linux-gnuabi64
  <<: *stable_cross_compile_template

stable-powerpc-unknown-linux-gnu:
  variables:
    PACKAGES: gcc-powerpc-linux-gnu
    TARGET: powerpc-unknown-linux-gnu
  <<: *stable_cross_compile_template

stable-powerpc64-unknown-linux-gnu:
  variables:
    PACKAGES: gcc-powerpc64-linux-gnu
    TARGET: powerpc64-unknown-linux-gnu
  <<: *stable_cross_compile_template

stable-powerpc64le-unknown-linux-gnu:
  variables:
    PACKAGES: gcc-powerpc64le-linux-gnu
    TARGET: powerpc64le-unknown-linux-gnu
  <<: *stable_cross_compile_template

stable-riscv64gc-unknown-linux-gnu:
  variables:
    PACKAGES: gcc-riscv64-linux-gnu
    TARGET: riscv64gc-unknown-linux-gnu
  <<: *stable_cross_compile_template

stable-s390x-unknown-linux-gnu:
  variables:
    PACKAGES: gcc-s390x-linux-gnu
    TARGET: s390x-unknown-linux-gnu
  <<: *stable_cross_compile_template

stable-sparc64-unknown-linux-gnu:
  variables:
    PACKAGES: gcc-sparc64-linux-gnu
    TARGET: sparc64-unknown-linux-gnu
  <<: *stable_cross_compile_template

stable-x86_64-unknown-linux-gnu:
  image: amd64/rust:slim-buster
  stage: stable
  <<: *x86_64-unknown-linux-gnu-template

## WebAssembly

stable-wasm32-wasi:
  image: amd64/rust:slim-buster
  stage: stable
  <<: *wasm32-wasi_template

## Windows

stable-x86_64-pc-windows-msvc:
  stage: stable
  variables:
    TARGET: x86_64-pc-windows-msvc
  <<: *windows_msvc_template

stable-i686-pc-windows-msvc:
  stage: stable
  variables:
    TARGET: i686-pc-windows-msvc
  <<: *windows_msvc_template

# Minimum Supported Rust Version

## Linux

msrv-aarch64-unknown-linux-gnu:
  variables:
    PACKAGES: gcc-aarch64-linux-gnu
    TARGET: aarch64-unknown-linux-gnu
  <<: *msrv_cross_compile_template

msrv-arm-unknown-linux-gnueabi:
  variables:
    PACKAGES: gcc-arm-linux-gnueabi
    TARGET: arm-unknown-linux-gnueabi
  <<: *msrv_cross_compile_template

msrv-arm-unknown-linux-gnueabihf:
  variables:
    PACKAGES: gcc-arm-linux-gnueabihf
    TARGET: arm-unknown-linux-gnueabihf
  <<: *msrv_cross_compile_template

msrv-armv5te-unknown-linux-gnueabi:
  variables:
    PACKAGES: gcc-arm-linux-gnueabi
    TARGET: armv5te-unknown-linux-gnueabi
  <<: *msrv_cross_compile_template

msrv-armv7-unknown-linux-gnueabi:
  variables:
    PACKAGES: gcc-arm-linux-gnueabi
    TARGET: armv7-unknown-linux-gnueabi
  <<: *msrv_cross_compile_template

msrv-armv7-unknown-linux-gnueabihf:
  variables:
    PACKAGES: gcc-arm-linux-gnueabihf
    TARGET: armv7-unknown-linux-gnueabihf
  <<: *msrv_cross_compile_template

msrv-i586-unknown-linux-gnu:
  variables:
    PACKAGES: gcc-i686-linux-gnu
    TARGET: i586-unknown-linux-gnu
  <<: *msrv_cross_compile_template

msrv-i686-unknown-linux-gnu:
  variables:
    PACKAGES: gcc-i686-linux-gnu
    TARGET: i686-unknown-linux-gnu
  <<: *msrv_cross_compile_template

msrv-mips-unknown-linux-gnu:
  variables:
    PACKAGES: gcc-mips-linux-gnu
    TARGET: mips-unknown-linux-gnu
  <<: *msrv_cross_compile_template

msrv-mipsel-unknown-linux-gnu:
  variables:
    PACKAGES: gcc-mipsel-linux-gnu
    TARGET: mipsel-unknown-linux-gnu
  <<: *msrv_cross_compile_template

msrv-mips64-unknown-linux-gnuabi64:
  variables:
    PACKAGES: gcc-mips64-linux-gnuabi64
    TARGET: mips64-unknown-linux-gnuabi64
  <<: *msrv_cross_compile_template

msrv-mips64el-unknown-linux-gnuabi64:
  variables:
    PACKAGES: gcc-mips64el-linux-gnuabi64
    TARGET: mips64el-unknown-linux-gnuabi64
  <<: *msrv_cross_compile_template

msrv-powerpc-unknown-linux-gnu:
  variables:
    PACKAGES: gcc-powerpc-linux-gnu
    TARGET: powerpc-unknown-linux-gnu
  <<: *msrv_cross_compile_template

msrv-powerpc64-unknown-linux-gnu:
  variables:
    PACKAGES: gcc-powerpc64-linux-gnu
    TARGET: powerpc64-unknown-linux-gnu
  <<: *msrv_cross_compile_template

msrv-powerpc64le-unknown-linux-gnu:
  variables:
    PACKAGES: gcc-powerpc64le-linux-gnu
    TARGET: powerpc64le-unknown-linux-gnu
  <<: *msrv_cross_compile_template

msrv-riscv64gc-unknown-linux-gnu:
  variables:
    PACKAGES: gcc-riscv64-linux-gnu
    TARGET: riscv64gc-unknown-linux-gnu
  <<: *msrv_cross_compile_template

msrv-s390x-unknown-linux-gnu:
  variables:
    PACKAGES: gcc-s390x-linux-gnu
    TARGET: s390x-unknown-linux-gnu
  <<: *msrv_cross_compile_template

msrv-sparc64-unknown-linux-gnu:
  variables:
    PACKAGES: gcc-sparc64-linux-gnu
    TARGET: sparc64-unknown-linux-gnu
  <<: *msrv_cross_compile_template

msrv-x86_64-unknown-linux-gnu:
  image: amd64/rust:slim-buster
  stage: msrv
  <<: *x86_64-unknown-linux-gnu-template

## WebAssembly

msrv-wasm32-wasi:
  image: amd64/rust:slim-buster
  stage: msrv
  <<: *wasm32-wasi_template

## Windows

msrv-x86_64-pc-windows-msvc:
  stage: msrv
  variables:
    TARGET: x86_64-pc-windows-msvc
  <<: *windows_msvc_template

msrv-i686-pc-windows-msvc:
  stage: msrv
  variables:
    TARGET: i686-pc-windows-msvc
  <<: *windows_msvc_template

# Nightly

## Linux

nightly-x86_64-unknown-linux-gnu:
  stage: nightly
  image: rustlang/rust:nightly-buster-slim
  <<: *x86_64-unknown-linux-gnu-template

## WebAssembly

nightly-wasm32-wasi:
  stage: nightly
  image: rustlang/rust:nightly-buster-slim
  <<: *wasm32-wasi_template
