stages:
  - stable
  - msrv # Minimum Supported Rust Version
  - nightly

variables:
  CARGO_HOME: ${CI_PROJECT_DIR}/cargo
  MSRV: '1.43'

# Templates

.cross_compile_template: &cross_compile_template
  image: ubuntu:groovy
  cache:
    key: ${CI_JOB_NAME}
    paths:
      - target/${TARGET}
  before_script:
    - >
      apt update -y;
      apt install -y curl make;
      curl https://sh.rustup.rs -sSf > install.sh;
      sh install.sh -y --default-toolchain ${CHANNEL} --profile minimal -t ${TARGET};
      if [[ ${#PACKAGES[@]} -ne 0 ]]; then
        apt install -y qemu-user ${PACKAGES};
      fi;
  script:
    - source ${CARGO_HOME}/env
    - make test.${TARGET}

.wasm32-wasi_template: &wasm32-wasi_template
  variables:
    WASMTIME_VERSION: 0.21.0
  cache:
    key: ${CI_JOB_NAME}
    paths:
      - target/wasm32-wasi
  before_script:
    - rustc --version
    - rustup target add wasm32-wasi
    - apt update -y
    - apt install -y curl make xz-utils
    - curl -L "https://github.com/bytecodealliance/wasmtime/releases/download/v${WASMTIME_VERSION}/wasmtime-v${WASMTIME_VERSION}-x86_64-linux.tar.xz" > wasmtime-v${WASMTIME_VERSION}-x86_64-linux.tar.xz
    - tar -xvf wasmtime-v${WASMTIME_VERSION}-x86_64-linux.tar.xz
    - mv wasmtime-v${WASMTIME_VERSION}-x86_64-linux/wasmtime /usr/bin/
  script:
    - make test.wasm32-wasi

# TODO: Support MSRV
.windows_msvc_template: &windows_msvc_template
  tags:
    - shared-windows
    - windows
  cache:
    key: ${CI_JOB_NAME}
    paths:
      - target/${TARGET}
  before_script:
    - Remove-Item Alias:curl
    - choco install make -y
    - curl --proto '=https' --tlsv1.2 -sSf https://win.rustup.rs/x86_64 -o rustup-init.exe
    - ./rustup-init.exe -y -t ${TARGET} --default-toolchain stable --profile minimal
    - $ENV:Path += "${CI_PROJECT_DIR}/cargo/bin"
  script:
    - make test.${TARGET}

# Stable

## Linux

stable-aarch64-unknown-linux-gnu:
  stage: stable
  variables:
    CHANNEL: stable
    PACKAGES: gcc-aarch64-linux-gnu
    TARGET: aarch64-unknown-linux-gnu
  <<: *cross_compile_template

stable-arm-unknown-linux-gnueabi:
  stage: stable
  variables:
    CHANNEL: stable
    PACKAGES: gcc-arm-linux-gnueabi
    TARGET: arm-unknown-linux-gnueabi
  <<: *cross_compile_template

stable-arm-unknown-linux-gnueabihf:
  stage: stable
  variables:
    CHANNEL: stable
    PACKAGES: gcc-arm-linux-gnueabihf
    TARGET: arm-unknown-linux-gnueabihf
  <<: *cross_compile_template

stable-armv5te-unknown-linux-gnueabi:
  stage: stable
  variables:
    CHANNEL: stable
    PACKAGES: gcc-arm-linux-gnueabi
    TARGET: armv5te-unknown-linux-gnueabi
  <<: *cross_compile_template

stable-armv7-unknown-linux-gnueabi:
  stage: stable
  variables:
    CHANNEL: stable
    PACKAGES: gcc-arm-linux-gnueabi
    TARGET: armv7-unknown-linux-gnueabi
  <<: *cross_compile_template

stable-armv7-unknown-linux-gnueabihf:
  stage: stable
  variables:
    CHANNEL: stable
    PACKAGES: gcc-arm-linux-gnueabihf
    TARGET: armv7-unknown-linux-gnueabihf
  <<: *cross_compile_template

stable-i586-unknown-linux-gnu:
  stage: stable
  variables:
    CHANNEL: stable
    PACKAGES: gcc-i686-linux-gnu
    TARGET: i586-unknown-linux-gnu
  <<: *cross_compile_template

stable-i686-unknown-linux-gnu:
  stage: stable
  variables:
    CHANNEL: stable
    PACKAGES: gcc-i686-linux-gnu
    TARGET: i686-unknown-linux-gnu
  <<: *cross_compile_template

stable-mips-unknown-linux-gnu:
  stage: stable
  variables:
    PACKAGES: gcc-mips-linux-gnu
    TARGET: mips-unknown-linux-gnu
  <<: *cross_compile_template

stable-mipsel-unknown-linux-gnu:
  stage: stable
  variables:
    CHANNEL: stable
    PACKAGES: gcc-mipsel-linux-gnu
    TARGET: mipsel-unknown-linux-gnu
  <<: *cross_compile_template

stable-mips64-unknown-linux-gnuabi64:
  stage: stable
  variables:
    CHANNEL: stable
    PACKAGES: gcc-mips64-linux-gnuabi64
    TARGET: mips64-unknown-linux-gnuabi64
  <<: *cross_compile_template

stable-mips64el-unknown-linux-gnuabi64:
  stage: stable
  variables:
    CHANNEL: stable
    PACKAGES: gcc-mips64el-linux-gnuabi64
    TARGET: mips64el-unknown-linux-gnuabi64
  <<: *cross_compile_template

stable-powerpc-unknown-linux-gnu:
  stage: stable
  variables:
    CHANNEL: stable
    PACKAGES: gcc-powerpc-linux-gnu
    TARGET: powerpc-unknown-linux-gnu
  <<: *cross_compile_template

stable-powerpc64-unknown-linux-gnu:
  stage: stable
  variables:
    CHANNEL: stable
    PACKAGES: gcc-powerpc64-linux-gnu
    TARGET: powerpc64-unknown-linux-gnu
  <<: *cross_compile_template

stable-powerpc64le-unknown-linux-gnu:
  stage: stable
  variables:
    CHANNEL: stable
    PACKAGES: gcc-powerpc64le-linux-gnu
    TARGET: powerpc64le-unknown-linux-gnu
  <<: *cross_compile_template

stable-riscv64gc-unknown-linux-gnu:
  stage: stable
  variables:
    CHANNEL: stable
    PACKAGES: gcc-riscv64-linux-gnu
    TARGET: riscv64gc-unknown-linux-gnu
  <<: *cross_compile_template

stable-s390x-unknown-linux-gnu:
  stage: stable
  variables:
    CHANNEL: stable
    PACKAGES: gcc-s390x-linux-gnu
    TARGET: s390x-unknown-linux-gnu
  <<: *cross_compile_template

stable-sparc64-unknown-linux-gnu:
  stage: stable
  variables:
    CHANNEL: stable
    PACKAGES: gcc-sparc64-linux-gnu
    TARGET: sparc64-unknown-linux-gnu
  <<: *cross_compile_template

stable-x86_64-unknown-linux-gnu:
  stage: stable
  variables:
    CHANNEL: stable
    TARGET: x86_64-unknown-linux-gnu
  <<: *cross_compile_template

stable-x86_64-unknown-linux-musl:
  stage: stable
  variables:
    CHANNEL: stable
    TARGET: x86_64-unknown-linux-musl
  <<: *cross_compile_template

## WebAssembly

stable-wasm32-wasi:
  image: amd64/rust:slim-buster
  stage: stable
  <<: *wasm32-wasi_template

## Windows

stable-x86_64-pc-windows-msvc:
  stage: stable
  variables:
    TARGET: x86_64-pc-windows-msvc
  <<: *windows_msvc_template

stable-i686-pc-windows-msvc:
  stage: stable
  variables:
    TARGET: i686-pc-windows-msvc
  <<: *windows_msvc_template

# Minimum Supported Rust Version

## Linux

msrv-aarch64-unknown-linux-gnu:
  stage: msrv
  variables:
    CHANNEL: ${MSRV}
    PACKAGES: gcc-aarch64-linux-gnu
    TARGET: aarch64-unknown-linux-gnu
  <<: *cross_compile_template

msrv-arm-unknown-linux-gnueabi:
  stage: msrv
  variables:
    CHANNEL: ${MSRV}
    PACKAGES: gcc-arm-linux-gnueabi
    TARGET: arm-unknown-linux-gnueabi
  <<: *cross_compile_template

msrv-arm-unknown-linux-gnueabihf:
  stage: msrv
  variables:
    CHANNEL: ${MSRV}
    PACKAGES: gcc-arm-linux-gnueabihf
    TARGET: arm-unknown-linux-gnueabihf
  <<: *cross_compile_template

msrv-armv5te-unknown-linux-gnueabi:
  stage: msrv
  variables:
    CHANNEL: ${MSRV}
    PACKAGES: gcc-arm-linux-gnueabi
    TARGET: armv5te-unknown-linux-gnueabi
  <<: *cross_compile_template

msrv-armv7-unknown-linux-gnueabi:
  stage: msrv
  variables:
    CHANNEL: ${MSRV}
    PACKAGES: gcc-arm-linux-gnueabi
    TARGET: armv7-unknown-linux-gnueabi
  <<: *cross_compile_template

msrv-armv7-unknown-linux-gnueabihf:
  stage: msrv
  variables:
    CHANNEL: ${MSRV}
    PACKAGES: gcc-arm-linux-gnueabihf
    TARGET: armv7-unknown-linux-gnueabihf
  <<: *cross_compile_template

msrv-i586-unknown-linux-gnu:
  stage: msrv
  variables:
    CHANNEL: ${MSRV}
    PACKAGES: gcc-i686-linux-gnu
    TARGET: i586-unknown-linux-gnu
  <<: *cross_compile_template

msrv-i686-unknown-linux-gnu:
  stage: msrv
  variables:
    CHANNEL: ${MSRV}
    PACKAGES: gcc-i686-linux-gnu
    TARGET: i686-unknown-linux-gnu
  <<: *cross_compile_template

msrv-mips-unknown-linux-gnu:
  stage: msrv
  variables:
    CHANNEL: ${MSRV}
    PACKAGES: gcc-mips-linux-gnu
    TARGET: mips-unknown-linux-gnu
  <<: *cross_compile_template

msrv-mipsel-unknown-linux-gnu:
  stage: msrv
  variables:
    CHANNEL: ${MSRV}
    PACKAGES: gcc-mipsel-linux-gnu
    TARGET: mipsel-unknown-linux-gnu
  <<: *cross_compile_template

msrv-mips64-unknown-linux-gnuabi64:
  stage: msrv
  variables:
    CHANNEL: ${MSRV}
    PACKAGES: gcc-mips64-linux-gnuabi64
    TARGET: mips64-unknown-linux-gnuabi64
  <<: *cross_compile_template

msrv-mips64el-unknown-linux-gnuabi64:
  stage: msrv
  variables:
    CHANNEL: ${MSRV}
    PACKAGES: gcc-mips64el-linux-gnuabi64
    TARGET: mips64el-unknown-linux-gnuabi64
  <<: *cross_compile_template

msrv-powerpc-unknown-linux-gnu:
  stage: msrv
  variables:
    CHANNEL: ${MSRV}
    PACKAGES: gcc-powerpc-linux-gnu
    TARGET: powerpc-unknown-linux-gnu
  <<: *cross_compile_template

msrv-powerpc64-unknown-linux-gnu:
  stage: msrv
  variables:
    CHANNEL: ${MSRV}
    PACKAGES: gcc-powerpc64-linux-gnu
    TARGET: powerpc64-unknown-linux-gnu
  <<: *cross_compile_template

msrv-powerpc64le-unknown-linux-gnu:
  stage: msrv
  variables:
    CHANNEL: ${MSRV}
    PACKAGES: gcc-powerpc64le-linux-gnu
    TARGET: powerpc64le-unknown-linux-gnu
  <<: *cross_compile_template

msrv-riscv64gc-unknown-linux-gnu:
  stage: msrv
  variables:
    CHANNEL: ${MSRV}
    PACKAGES: gcc-riscv64-linux-gnu
    TARGET: riscv64gc-unknown-linux-gnu
  <<: *cross_compile_template

msrv-s390x-unknown-linux-gnu:
  stage: msrv
  variables:
    CHANNEL: ${MSRV}
    PACKAGES: gcc-s390x-linux-gnu
    TARGET: s390x-unknown-linux-gnu
  <<: *cross_compile_template

msrv-sparc64-unknown-linux-gnu:
  stage: msrv
  variables:
    CHANNEL: ${MSRV}
    PACKAGES: gcc-sparc64-linux-gnu
    TARGET: sparc64-unknown-linux-gnu
  <<: *cross_compile_template

msrv-x86_64-unknown-linux-gnu:
  stage: msrv
  variables:
    CHANNEL: ${MSRV}
    TARGET: x86_64-unknown-linux-gnu
  <<: *cross_compile_template

msrv-x86_64-unknown-linux-musl:
  stage: msrv
  variables:
    CHANNEL: ${MSRV}
    TARGET: x86_64-unknown-linux-musl
  <<: *cross_compile_template

## WebAssembly

msrv-wasm32-wasi:
  image: amd64/rust:1.43.0-slim-buster
  stage: msrv
  <<: *wasm32-wasi_template

## Windows

# msrv-x86_64-pc-windows-msvc:
#   stage: msrv
#   variables:
#     TARGET: x86_64-pc-windows-msvc
#   <<: *windows_msvc_template

# msrv-i686-pc-windows-msvc:
#   stage: msrv
#   variables:
#     TARGET: i686-pc-windows-msvc
#   <<: *windows_msvc_template

# Nightly

## Linux

nightly-aarch64-unknown-linux-gnu:
  stage: nightly
  variables:
    CHANNEL: nightly
    PACKAGES: gcc-aarch64-linux-gnu
    TARGET: aarch64-unknown-linux-gnu
  <<: *cross_compile_template

nightly-arm-unknown-linux-gnueabi:
  stage: nightly
  variables:
    CHANNEL: nightly
    PACKAGES: gcc-arm-linux-gnueabi
    TARGET: arm-unknown-linux-gnueabi
  <<: *cross_compile_template

nightly-arm-unknown-linux-gnueabihf:
  stage: nightly
  variables:
    CHANNEL: nightly
    PACKAGES: gcc-arm-linux-gnueabihf
    TARGET: arm-unknown-linux-gnueabihf
  <<: *cross_compile_template

nightly-armv5te-unknown-linux-gnueabi:
  stage: nightly
  variables:
    CHANNEL: nightly
    PACKAGES: gcc-arm-linux-gnueabi
    TARGET: armv5te-unknown-linux-gnueabi
  <<: *cross_compile_template

nightly-armv7-unknown-linux-gnueabi:
  stage: nightly
  variables:
    CHANNEL: nightly
    PACKAGES: gcc-arm-linux-gnueabi
    TARGET: armv7-unknown-linux-gnueabi
  <<: *cross_compile_template

nightly-armv7-unknown-linux-gnueabihf:
  stage: nightly
  variables:
    CHANNEL: nightly
    PACKAGES: gcc-arm-linux-gnueabihf
    TARGET: armv7-unknown-linux-gnueabihf
  <<: *cross_compile_template

nightly-i586-unknown-linux-gnu:
  stage: nightly
  variables:
    CHANNEL: nightly
    PACKAGES: gcc-i686-linux-gnu
    TARGET: i586-unknown-linux-gnu
  <<: *cross_compile_template

nightly-i686-unknown-linux-gnu:
  stage: nightly
  variables:
    CHANNEL: nightly
    PACKAGES: gcc-i686-linux-gnu
    TARGET: i686-unknown-linux-gnu
  <<: *cross_compile_template

nightly-mips-unknown-linux-gnu:
  stage: nightly
  variables:
    CHANNEL: nightly
    PACKAGES: gcc-mips-linux-gnu
    TARGET: mips-unknown-linux-gnu
  <<: *cross_compile_template

nightly-mipsel-unknown-linux-gnu:
  stage: nightly
  variables:
    CHANNEL: nightly
    PACKAGES: gcc-mipsel-linux-gnu
    TARGET: mipsel-unknown-linux-gnu
  <<: *cross_compile_template

nightly-mips64-unknown-linux-gnuabi64:
  stage: nightly
  variables:
    CHANNEL: nightly
    PACKAGES: gcc-mips64-linux-gnuabi64
    TARGET: mips64-unknown-linux-gnuabi64
  <<: *cross_compile_template

nightly-mips64el-unknown-linux-gnuabi64:
  stage: nightly
  variables:
    CHANNEL: nightly
    PACKAGES: gcc-mips64el-linux-gnuabi64
    TARGET: mips64el-unknown-linux-gnuabi64
  <<: *cross_compile_template

nightly-powerpc-unknown-linux-gnu:
  stage: nightly
  variables:
    CHANNEL: nightly
    PACKAGES: gcc-powerpc-linux-gnu
    TARGET: powerpc-unknown-linux-gnu
  <<: *cross_compile_template

nightly-powerpc64-unknown-linux-gnu:
  stage: nightly
  variables:
    CHANNEL: nightly
    PACKAGES: gcc-powerpc64-linux-gnu
    TARGET: powerpc64-unknown-linux-gnu
  <<: *cross_compile_template

nightly-powerpc64le-unknown-linux-gnu:
  stage: nightly
  variables:
    CHANNEL: nightly
    PACKAGES: gcc-powerpc64le-linux-gnu
    TARGET: powerpc64le-unknown-linux-gnu
  <<: *cross_compile_template

nightly-riscv64gc-unknown-linux-gnu:
  stage: nightly
  variables:
    CHANNEL: nightly
    PACKAGES: gcc-riscv64-linux-gnu
    TARGET: riscv64gc-unknown-linux-gnu
  <<: *cross_compile_template

nightly-s390x-unknown-linux-gnu:
  stage: nightly
  variables:
    CHANNEL: nightly
    PACKAGES: gcc-s390x-linux-gnu
    TARGET: s390x-unknown-linux-gnu
  <<: *cross_compile_template

nightly-sparc64-unknown-linux-gnu:
  stage: nightly
  variables:
    CHANNEL: nightly
    PACKAGES: gcc-sparc64-linux-gnu
    TARGET: sparc64-unknown-linux-gnu
  <<: *cross_compile_template

nightly-x86_64-unknown-linux-gnu:
  stage: nightly
  variables:
    CHANNEL: nightly
    TARGET: x86_64-unknown-linux-gnu
  <<: *cross_compile_template

nightly-x86_64-unknown-linux-musl:
  stage: nightly
  variables:
    CHANNEL: nightly
    TARGET: x86_64-unknown-linux-musl
  <<: *cross_compile_template

## WebAssembly

nightly-wasm32-wasi:
  stage: nightly
  image: rustlang/rust:nightly-buster-slim
  <<: *wasm32-wasi_template
