stages:
  - stable
  - msrv # Minimum Supported Rust Version
  - nightly

variables:
  CARGO_HOME: ${CI_PROJECT_DIR}/cargo
  MSRV: '1.43'
  WASMTIME_VERSION: 0.21.0

# Linux

.linux_cross_compile_template: &linux_cross_compile_template
  image: ubuntu:groovy
  cache:
    key: ${CI_JOB_STAGE}-${TARGET}
    paths:
      - target/${TARGET}
  before_script:
    - >
      apt update -y;
      apt install -y curl make;
      curl https://sh.rustup.rs -sSf > install.sh;
      sh install.sh -y --default-toolchain ${CHANNEL} --profile minimal -t ${TARGET};
      if [[ ${#PACKAGES[@]} -ne 0 ]]; then
        apt install -y qemu-user ${PACKAGES};
      fi;
  script:
    - source ${CARGO_HOME}/env
    - make test.${TARGET}

.linux-matrix_template: &linux_matrix_template
  parallel:
    matrix:
      - PACKAGES: gcc-aarch64-linux-gnu
        TARGET: aarch64-unknown-linux-gnu
      - PACKAGES: gcc-arm-linux-gnueabi
        TARGET: arm-unknown-linux-gnueabi
      - PACKAGES: gcc-arm-linux-gnueabihf
        TARGET: arm-unknown-linux-gnueabihf
      - PACKAGES: gcc-arm-linux-gnueabi
        TARGET: armv5te-unknown-linux-gnueabi
      - PACKAGES: gcc-arm-linux-gnueabi
        TARGET: armv7-unknown-linux-gnueabi
      - PACKAGES: gcc-arm-linux-gnueabihf
        TARGET: armv7-unknown-linux-gnueabihf
      - PACKAGES: gcc-i686-linux-gnu
        TARGET: i586-unknown-linux-gnu
      - PACKAGES: gcc-i686-linux-gnu
        TARGET: i686-unknown-linux-gnu
      - PACKAGES: gcc-mips-linux-gnu
        TARGET: mips-unknown-linux-gnu
      - PACKAGES: gcc-mipsel-linux-gnu
        TARGET: mipsel-unknown-linux-gnu
      - PACKAGES: gcc-mips64-linux-gnuabi64
        TARGET: mips64-unknown-linux-gnuabi64
      - PACKAGES: gcc-mips64el-linux-gnuabi64
        TARGET: mips64el-unknown-linux-gnuabi64
      - PACKAGES: gcc-powerpc-linux-gnu
        TARGET: powerpc-unknown-linux-gnu
      - PACKAGES: gcc-powerpc64-linux-gnu
        TARGET: powerpc64-unknown-linux-gnu
      - PACKAGES: gcc-powerpc64le-linux-gnu
        TARGET: powerpc64le-unknown-linux-gnu
      - PACKAGES: gcc-riscv64-linux-gnu
        TARGET: riscv64gc-unknown-linux-gnu
      - PACKAGES: gcc-s390x-linux-gnu
        TARGET: s390x-unknown-linux-gnu
      - PACKAGES: gcc-sparc64-linux-gnu
        TARGET: sparc64-unknown-linux-gnu
      - PACKAGES: gcc
        TARGET: x86_64-unknown-linux-gnu
      - PACKAGES: gcc
        TARGET: x86_64-unknown-linux-musl

stable-linux:
  stage: stable
  variables:
    CHANNEL: stable
  <<: *linux_cross_compile_template
  <<: *linux_matrix_template

msrv-linux:
  stage: msrv
  variables:
    CHANNEL: ${MSRV}
  <<: *linux_cross_compile_template
  <<: *linux_matrix_template

nightly-linux:
  stage: nightly
  variables:
    CHANNEL: nightly
  <<: *linux_cross_compile_template
  <<: *linux_matrix_template

# WebAssembly

.wasm32-wasi_template: &wasm32-wasi_template
  image: ubuntu:groovy
  cache:
    key: ${CI_JOB_STAGE}-wasm32-wasi
    paths:
      - target/wasm32-wasi
  before_script:
    - apt update -y
    - apt install -y curl make xz-utils
    - curl https://sh.rustup.rs -sSf > install.sh
    - sh install.sh -y --default-toolchain ${CHANNEL} --profile minimal -t wasm32-wasi
    - curl -L "https://github.com/bytecodealliance/wasmtime/releases/download/v${WASMTIME_VERSION}/wasmtime-v${WASMTIME_VERSION}-x86_64-linux.tar.xz" > wasmtime-v${WASMTIME_VERSION}-x86_64-linux.tar.xz
    - tar -xvf wasmtime-v${WASMTIME_VERSION}-x86_64-linux.tar.xz
    - mv wasmtime-v${WASMTIME_VERSION}-x86_64-linux/wasmtime /usr/bin/
  script:
    - make test.wasm32-wasi

stable-wasm32-wasi:
  stage: stable
  variables:
    CHANNEL: stable
  <<: *wasm32-wasi_template

msrv-wasm32-wasi:
  stage: msrv
  variables:
    CHANNEL: ${MSRV}
  <<: *wasm32-wasi_template

nightly-wasm32-wasi:
  stage: nightly
  variables:
    CHANNEL: nightly
  <<: *wasm32-wasi_template

# Windows

.windows_msvc_template: &windows_msvc_template
  tags:
    - shared-windows
    - windows
  cache:
    key: ${CI_JOB_NAME}
    paths:
      - target/${TARGET}
  before_script:
    - Remove-Item Alias:curl
    - choco install make -y
    - curl --proto '=https' --tlsv1.2 -sSf https://win.rustup.rs/x86_64 -o rustup-init.exe
    - ./rustup-init.exe -y -t ${TARGET} --default-toolchain ${CHANNEL} --profile minimal
    - $ENV:Path += "${CI_PROJECT_DIR}/cargo/bin"
  script:
    - make test.${TARGET}

.windows_matrix_template: &windows_matrix_template
  parallel:
    matrix:
      - TARGET: [x86_64-pc-windows-msvc, i686-pc-windows-msvc]

stable-windows-msvc:
  stage: stable
  variables:
    CHANNEL: stable
  <<: *windows_msvc_template
  <<: *windows_matrix_template

## Windows

# msrv-x86_64-pc-windows-msvc:
#   stage: msrv
#   variables:
#     TARGET: x86_64-pc-windows-msvc
#   <<: *windows_msvc_template

# msrv-i686-pc-windows-msvc:
#   stage: msrv
#   variables:
#     TARGET: i686-pc-windows-msvc
#   <<: *windows_msvc_template
