stages:
  - test
  - msrv # Minimum Supported Rust Version

variables:
  CARGO_HOME: ${CI_PROJECT_DIR}/cargo

.cross_compile_template: &cross_compile_template
  image: amd64/ubuntu:groovy
  stage: ${STAGE}
  cache:
    paths:
      - target/${TARGET}
  before_script:
    - apt update -y
    - apt install -y curl make qemu-user ${PACKAGES}
    - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > setup.sh
    - sh setup.sh -y -t ${TARGET} --default-toolchain stable --profile minimal
    - source ${CI_PROJECT_DIR}/cargo/env
  script:
    - make test.${TARGET}

.wasm32-wasi_template: &wasm32-wasi_template
  image: amd64/rust:slim-buster
  stage: ${STAGE}
  variables:
    WASMTIME_VERSION: 0.21.0
  cache:
    paths:
      - target/wasm32-wasi
  before_script:
    - rustc --version
    - rustup target add wasm32-wasi
    - apt update -y
    - apt install -y curl make xz-utils
    - curl -L "https://github.com/bytecodealliance/wasmtime/releases/download/v${WASMTIME_VERSION}/wasmtime-v${WASMTIME_VERSION}-x86_64-linux.tar.xz" > wasmtime-v${WASMTIME_VERSION}-x86_64-linux.tar.xz
    - tar -xvf wasmtime-v${WASMTIME_VERSION}-x86_64-linux.tar.xz
    - mv wasmtime-v${WASMTIME_VERSION}-x86_64-linux/wasmtime /usr/bin/
  script:
    - make test.wasm32-wasi

.x86_64-unknown-linux-gnu-template: &x86_64-unknown-linux-gnu-template
  image: amd64/rust:slim-buster
  stage: ${STAGE}
  cache:
    paths:
      - target/x86_64-unknown-linux-gnu
  before_script:
    - apt update -y
    - apt install -y make
    - rustc --version
  script:
    - make test.x86_64-unknown-linux-gnu

stable-aarch64-unknown-linux-gnu:
  variables:
    STAGE: test
    PACKAGES: gcc-aarch64-linux-gnu
    TARGET: aarch64-unknown-linux-gnu
  <<: *cross_compile_template

stable-arm-unknown-linux-gnueabi:
  variables:
    STAGE: test
    PACKAGES: gcc-arm-linux-gnueabi
    TARGET: arm-unknown-linux-gnueabi
  <<: *cross_compile_template

stable-arm-unknown-linux-gnueabihf:
  variables:
    STAGE: test
    PACKAGES: gcc-arm-linux-gnueabihf
    TARGET: arm-unknown-linux-gnueabihf
  <<: *cross_compile_template

stable-armv5te-unknown-linux-gnueabi:
  variables:
    STAGE: test
    PACKAGES: gcc-arm-linux-gnueabi
    TARGET: armv5te-unknown-linux-gnueabi
  <<: *cross_compile_template

stable-armv7-unknown-linux-gnueabi:
  variables:
    STAGE: test
    PACKAGES: gcc-arm-linux-gnueabi
    TARGET: armv7-unknown-linux-gnueabi
  <<: *cross_compile_template

stable-armv7-unknown-linux-gnueabihf:
  variables:
    STAGE: test
    PACKAGES: gcc-arm-linux-gnueabihf
    TARGET: armv7-unknown-linux-gnueabihf
  <<: *cross_compile_template

stable-i586-unknown-linux-gnu:
  variables:
    STAGE: test
    PACKAGES: gcc-i686-linux-gnu
    TARGET: i586-unknown-linux-gnu
  <<: *cross_compile_template

stable-i686-unknown-linux-gnu:
  variables:
    STAGE: test
    PACKAGES: gcc-i686-linux-gnu
    TARGET: i686-unknown-linux-gnu
  <<: *cross_compile_template

stable-mips-unknown-linux-gnu:
  variables:
    STAGE: test
    PACKAGES: gcc-mips-linux-gnu
    TARGET: mips-unknown-linux-gnu
  <<: *cross_compile_template

stable-mipsel-unknown-linux-gnu:
  variables:
    STAGE: test
    PACKAGES: gcc-mipsel-linux-gnu
    TARGET: mipsel-unknown-linux-gnu
  <<: *cross_compile_template

stable-mips64-unknown-linux-gnuabi64:
  variables:
    STAGE: test
    PACKAGES: gcc-mips64-linux-gnuabi64
    TARGET: mips64-unknown-linux-gnuabi64
  <<: *cross_compile_template

stable-mips64el-unknown-linux-gnuabi64:
  variables:
    STAGE: test
    PACKAGES: gcc-mips64el-linux-gnuabi64
    TARGET: mips64el-unknown-linux-gnuabi64
  <<: *cross_compile_template

stable-powerpc-unknown-linux-gnu:
  variables:
    STAGE: test
    PACKAGES: gcc-powerpc-linux-gnu
    TARGET: powerpc-unknown-linux-gnu
  <<: *cross_compile_template

stable-powerpc64-unknown-linux-gnu:
  variables:
    STAGE: test
    PACKAGES: gcc-powerpc64-linux-gnu
    TARGET: powerpc64-unknown-linux-gnu
  <<: *cross_compile_template

stable-powerpc64le-unknown-linux-gnu:
  variables:
    STAGE: test
    PACKAGES: gcc-powerpc64le-linux-gnu
    TARGET: powerpc64le-unknown-linux-gnu
  <<: *cross_compile_template

stable-riscv64gc-unknown-linux-gnu:
  variables:
    STAGE: test
    PACKAGES: gcc-riscv64-linux-gnu
    TARGET: riscv64gc-unknown-linux-gnu
  <<: *cross_compile_template

stable-s390x-unknown-linux-gnu:
  variables:
    STAGE: test
    PACKAGES: gcc-s390x-linux-gnu
    TARGET: s390x-unknown-linux-gnu
  <<: *cross_compile_template

stable-sparc64-unknown-linux-gnu:
  variables:
    STAGE: test
    PACKAGES: gcc-sparc64-linux-gnu
    TARGET: sparc64-unknown-linux-gnu
  <<: *cross_compile_template

stable-x86_64-unknown-linux-gnu:
  stage: test
  <<: *x86_64-unknown-linux-gnu-template

stable-wasm32-wasi:
  stage: test
  <<: *wasm32-wasi_template

nightly-x86_64-unknown-linux-gnu:
  stage: test
  image: rustlang/rust:nightly-buster-slim
  cache:
    paths:
      - target/x86_64-unknown-linux-gnu
  before_script:
    - apt update -y
    - apt install -y make
    - rustc --version
  script:
    - make test.x86_64-unknown-linux-gnu

nightly-wasm32-wasi:
  stage: test
  image: rustlang/rust:nightly-buster-slim
  <<: *wasm32-wasi_template

.windows_msvc_template: &windows_msvc_template
  tags:
    - shared-windows
    - windows
  cache:
    paths:
      - target/${TARGET}
  before_script:
    - Remove-Item Alias:curl
    - choco install make -y
    - curl --proto '=https' --tlsv1.2 -sSf https://win.rustup.rs/x86_64 -o rustup-init.exe
    - ./rustup-init.exe -y -t ${TARGET} --default-toolchain stable --profile minimal
    - $ENV:Path += "${CI_PROJECT_DIR}/cargo/bin"
  script:
    - make test.${TARGET}

stable-x86_64-pc-windows-msvc:
  variables:
    STAGE: test
    TARGET: x86_64-pc-windows-msvc
  <<: *windows_msvc_template

stable-i686-pc-windows-msvc:
  variables:
    STAGE: test
    TARGET: i686-pc-windows-msvc
  <<: *windows_msvc_template

# Minimum Supported Rust Version

msrv-aarch64-unknown-linux-gnu:
  variables:
    STAGE: msrv
    PACKAGES: gcc-aarch64-linux-gnu
    TARGET: aarch64-unknown-linux-gnu
  <<: *cross_compile_template

msrv-arm-unknown-linux-gnueabi:
  variables:
    STAGE: msrv
    PACKAGES: gcc-arm-linux-gnueabi
    TARGET: arm-unknown-linux-gnueabi
  <<: *cross_compile_template

msrv-arm-unknown-linux-gnueabihf:
  variables:
    STAGE: msrv
    PACKAGES: gcc-arm-linux-gnueabihf
    TARGET: arm-unknown-linux-gnueabihf
  <<: *cross_compile_template

msrv-armv5te-unknown-linux-gnueabi:
  variables:
    STAGE: msrv
    PACKAGES: gcc-arm-linux-gnueabi
    TARGET: armv5te-unknown-linux-gnueabi
  <<: *cross_compile_template

msrv-armv7-unknown-linux-gnueabi:
  variables:
    STAGE: msrv
    PACKAGES: gcc-arm-linux-gnueabi
    TARGET: armv7-unknown-linux-gnueabi
  <<: *cross_compile_template

msrv-armv7-unknown-linux-gnueabihf:
  variables:
    STAGE: msrv
    PACKAGES: gcc-arm-linux-gnueabihf
    TARGET: armv7-unknown-linux-gnueabihf
  <<: *cross_compile_template

msrv-i586-unknown-linux-gnu:
  variables:
    STAGE: msrv
    PACKAGES: gcc-i686-linux-gnu
    TARGET: i586-unknown-linux-gnu
  <<: *cross_compile_template

msrv-i686-unknown-linux-gnu:
  variables:
    STAGE: msrv
    PACKAGES: gcc-i686-linux-gnu
    TARGET: i686-unknown-linux-gnu
  <<: *cross_compile_template

msrv-mips-unknown-linux-gnu:
  variables:
    STAGE: msrv
    PACKAGES: gcc-mips-linux-gnu
    TARGET: mips-unknown-linux-gnu
  <<: *cross_compile_template

msrv-mipsel-unknown-linux-gnu:
  variables:
    STAGE: msrv
    PACKAGES: gcc-mipsel-linux-gnu
    TARGET: mipsel-unknown-linux-gnu
  <<: *cross_compile_template

msrv-mips64-unknown-linux-gnuabi64:
  variables:
    STAGE: msrv
    PACKAGES: gcc-mips64-linux-gnuabi64
    TARGET: mips64-unknown-linux-gnuabi64
  <<: *cross_compile_template

msrv-mips64el-unknown-linux-gnuabi64:
  variables:
    STAGE: msrv
    PACKAGES: gcc-mips64el-linux-gnuabi64
    TARGET: mips64el-unknown-linux-gnuabi64
  <<: *cross_compile_template

msrv-powerpc-unknown-linux-gnu:
  variables:
    STAGE: msrv
    PACKAGES: gcc-powerpc-linux-gnu
    TARGET: powerpc-unknown-linux-gnu
  <<: *cross_compile_template

msrv-powerpc64-unknown-linux-gnu:
  variables:
    STAGE: msrv
    PACKAGES: gcc-powerpc64-linux-gnu
    TARGET: powerpc64-unknown-linux-gnu
  <<: *cross_compile_template

msrv-powerpc64le-unknown-linux-gnu:
  variables:
    STAGE: msrv
    PACKAGES: gcc-powerpc64le-linux-gnu
    TARGET: powerpc64le-unknown-linux-gnu
  <<: *cross_compile_template

msrv-riscv64gc-unknown-linux-gnu:
  variables:
    STAGE: msrv
    PACKAGES: gcc-riscv64-linux-gnu
    TARGET: riscv64gc-unknown-linux-gnu
  <<: *cross_compile_template

msrv-s390x-unknown-linux-gnu:
  variables:
    STAGE: msrv
    PACKAGES: gcc-s390x-linux-gnu
    TARGET: s390x-unknown-linux-gnu
  <<: *cross_compile_template

msrv-sparc64-unknown-linux-gnu:
  variables:
    STAGE: msrv
    PACKAGES: gcc-sparc64-linux-gnu
    TARGET: sparc64-unknown-linux-gnu
  <<: *cross_compile_template

msrv-x86_64-unknown-linux-gnu:
  stage: msrv
  <<: *x86_64-unknown-linux-gnu-template

msrv-wasm32-wasi:
  stage: msrv
  image: amd64/rust:slim-buster
  <<: *wasm32-wasi_template

msrv-x86_64-pc-windows-msvc:
  variables:
    STAGE: msrv
    TARGET: x86_64-pc-windows-msvc
  <<: *windows_msvc_template

msrv-i686-pc-windows-msvc:
  variables:
    STAGE: msrv
    TARGET: i686-pc-windows-msvc
  <<: *windows_msvc_template
