stages:
  - test

variables:
  CARGO_HOME: ${CI_PROJECT_DIR}/cargo

cache:
  paths:
    - cargo/
    - target/

stable-i386:
  stage: test
  image: i386/rust:slim-buster
  script:
    - rust --version
    - cargo test --verbose

stable-amd64:
  stage: test
  image: rust:slim-buster
  script:
    - rust --version
    - cargo test --verbose

nightly-amd64:
  stage: test
  image: rustlang/rust:nightly-buster-slim
  script:
    - rust --version
    - cargo test --verbose
