stages:
  - stable
  - msrv # Minimum Supported Rust Version
  - nightly

variables:
  CARGO_HOME: ${CI_PROJECT_DIR}/cargo

include:
  - local: '/.gitlab/ci/template.yml'
  - local: '/.gitlab/ci/stable.yml'
  - local: '/.gitlab/ci/msrv.yml'
  - local: '/.gitlab/ci/nightly.yml'
