[package]
name = "ghash"
version = "0.0.1"
authors = ["glatan <glatan.edu@gmail.com>"]
edition = "2018"
license = "Apache-2.0 OR MIT"
readme = "README.md"
repository = "https://gitlab.com/glatan/ghash/"
homepage = "https://gitlab.com/glatan/ghash/"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "criterion"
harness = false
