[package]
name = "blake"
version = "0.1.0"
authors = ["glatan <glatan@protonmail.com>"]
edition = "2018"

[features]
minimal = []

[dependencies]
utils = { path = "../../utils" }

[dev-dependencies]
dev-utils = { path = "../../dev-utils" }
